config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  
  validates :name, presence: true
  validates :ingredient, presence: true
  validates :category, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  
  mount_uploader :picture, PictureUploader
  
  CATEGORIES = {
    'breakfast' => 'Breakfast',
    'main' => 'main',
    'dessert' => 'dessert',
    'side' => 'side'
  }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  
  def index
    @meals = Meal.all
  end
  
  def new
    @meal = Meal.new
  end
  
  def create 
    @meal = Meal.create(meal_params)
    if @meal.valid?
      redirect_to meals_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private
  
  def meal_params
    params.require(:meal).permit(:name, :ingredient, :category, :cost, :high_protein, :low_carb, :vegan, :picture)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mamakangkitchen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar navbar-light bg-faded">
     <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
     <div class="collapse navbar-toggleable-md" id="navbarResponsive">
       <%= link_to root_path, class: "navbar-brand" do %>
       <img src="https://storage.designcrowd.com/design_img/573834/205536/205536_3788811_573834_image.png" height="30" width="30" alt="" />
        Mama Kang's Kitchen
       <% end %>
    
       <ul class="nav navbar-nav float-xs-right">   
         <li class="nav-item">
           <%= link_to new_meal_path, class: 'nav-link' do %>
             New Meal
           <% end %>
         </li>
         <li class="nav-item">
           <%= link_to meals_path, class: 'nav-link' do %>
             Menu
           <% end %>
         </li>
       </ul>
       
     </div>
   </nav>
   
    <%= yield %>
    
    <br />
    <br class="clr" />
    <br />
    <div class="footer">
    <p>Made by <a href="mailto:arwen0603@gmail.com">Celia</a> with <span class="heart">&hearts;</span></p>
  </div>
  </body>
</html>

app/views/meals/index.html.erb
<% @meals.each do |meal| %>
<div class="col-xs-3">
<div class="booyah-box menu">
  <div class="ribbon"><span><%= number_to_currency meal.cost %></span></div>
  <%= image_tag meal.picture, class: "img-thumbnail" %>
  <h3><%= meal.name %></h3>
  <p><%= meal.ingredient %></p>

  <span class="tag tag-pill tag-default"><%= meal.category %></span>
  <% if meal.high_protein? %>
    <span class="tag tag-pill tag-info">High Protein</span>
  <% end %>
  <% if meal.low_carb? %>
    <span class="tag tag-pill tag-warning">Low Carb</span>
  <% end %>
  <% if meal.vegan? %>
    <span class="tag tag-pill tag-success">Vegan</span>
  <% end %>
</div>
</div>
<% end %>

app/views/meals/new.html.erb
<div class="booyah-box col-xs-6 offset-xs-3 meal">
    <h2>Create New Meal</h2>
    <br/>
    <%= simple_form_for @meal do |f| %>
    <%= f.input :name %>
    <%= f.input :ingredient %>
    <%= f.input :category, as: :select, collection: Meal::CATEGORIES %>
    <%= f.input :cost %>
    <%= f.input :high_protein, as: :boolean %>
    <%= f.input :low_carb, as: :boolean %>
    <%= f.input :vegan, as: :boolean %>
    <%= f.input :picture %>
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/static_pages/index.html.erb
<div class="fitness">
	<div class="fitness-inner">
  	<h1>Are you a fitness enthusiast...</h1>
  	<h2>but tired of boring chicken and broccoli?</h2>
	</div>
</div>

<div class="foodie">
	<div class="foodie-inner">
		<h1>Are you an Asian food junkie...</h1>
		<h2>but looking for less-greasy and low sodium dishes?</h2>
	</div>
</div>

<div class="vegan">
	<div class="vegan-inner">
		<h1>Are you intrigued by a plant based diet...</h1>
		<h2>but having no idea where to start?</h2>
	</div>
</div>

<div class="about">
	<div class="about-inner">
		<h1 class="about-title">Let us take care of your stomach!</h1>
		<div class="container">
			<div class="row">
		  <div class="col-md-3">
        <%= image_tag("oat.png",height: '100', width: '100') %>
				<br/>
				<h2>All natural</h2></div>
		  <div class="col-md-3">
        <%= image_tag("rice.png",height: '100', width: '100') %>
				<br/>
				<h2>Authentic</h2></div>
		  <div class="col-md-3">
        <%= image_tag("steak.png",height: '100', width: '100') %>
				<br/>
				<h2>Low carb</h2></div>
			<div class="col-md-3">
        <%= image_tag("mushrooms.png",height: '100', width: '100') %>
				<br/>
				<h2>Plant based</h2>
			</div>
		</div>

		<h1>Interested? Take a look at our menu</h1>
    <%= link_to "Menu", meals_path, class: 'btn btn-info btn-lg' %>
    
		</div>


	</div>

</div>